services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - ./backend/datastore/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: ./backend
      target: development
      dockerfile: ./Containerfile
    environment:
      PGHOST: db
      PGDATABASE: backend
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: ./frontend
      target: development
      dockerfile: ./Containerfile
      no_cache: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    volumes:
      - ./frontend/:/app
      - /app/node_modules
